import bcrypt from 'bcryptjs';

//To refresh data 
//localhost:5000/api/projects/seed
//localhost:5000/api/experiences/seed


const data = {
    users: [
        {
            name: 'Nick',
            email: 'nmak@ucsd.edu',
            password: bcrypt.hashSync('Perp0Pikmin', 8),
            isAdmin: true,
        },
        {
            name: 'Jenna',
            email: 'jmy001@ucsd.edu',
            password: bcrypt.hashSync('babe', 8),
            isAdmin: false,
        },
    ],
    projects: [
        {
            number: 0,
            name: 'Virus Shooter',
            role: 'Main Developer',
            tech: 'Unity3D, C#',
            image: '/images/virus_shooter.png',
            date: 'April 2021',
            dateShort: '4/2021',
            description: 'This Unity game was built for my VR class at UC San Diego. This project was an intro to basic game functionalities and based on the COVID-19 Virus. The player will try to shoot as many mutant viruses as they can before the timer runs out.',
            link: 'https://nmakucsd.github.io/Virus_Shooter/index.html',
            action: 'PLAY',
            active: true,
        },
        {
            number: 1,
            name: 'BulkUP E-commerce Web App',
            role: 'Developer and Designer',
            tech: 'MongoDB, Express, React, Node.js',
            image: '/images/BulkUP.png',
            date: 'September 2020 - April 2021',
            dateShort: '9/2020 - 4/2021',
            description: 'This is an E-commerce Web App built to connect produce sellers with restaurant and business owners in order to remove the middleman and allow both sides to have better business and pricing. Sellers are able to view and connect with restaurants nearby while buyers are able to easily see the selection of farmers and wholesale sellers nearby as well. This app is built with MongoDB, Express, React, and NodeJS.',
            link: 'https://my-bulkup-app.herokuapp.com/',
            action: 'VISIT SITE',
            active: true,
        },
        {
            number: 2,
            name: 'Wear a Mask!',
            role: 'Main Developer',
            tech: 'Unity3D, C#',
            image: '/images/WearAMask.png',
            date: 'January 2021',
            dateShort: '1/2021',
            description: 'This Unity game was built for my VR class at UC San Diego. This project needed to implement a simple game on social distancing. A deadly disease (much deadlier than COVID-19) has spread throughout the world and kills anyone who is within less than 6 feet (~2 meters) from an infected person that is not wearing a mask. The game is played in first person view in a 3D environment. People randomly spawn in front of the player, walking slowly towards them. The player\'s goal is to stare at them long enough for them to get reminded to put their mask on. If the person does not put their mask on before they get within 6 feet (~2 meters) from the player, the player gets infected and loses the game.',
            link: 'https://nmakucsd.github.io/Wear_A_Mask/index.html',
            action: 'PLAY',
            active: true,
        },
        {
            number: 3,
            name: 'Jelly Bumper',
            role: 'Main Developer',
            tech: 'Unity3D, C#',
            image: '/images/JellyBumpers.png',
            date: 'November 2020',
            dateShort: '11/2020',
            description: 'This Unity game was built by me to start TritonXR\'s, a VR/AR organization in my university, Unity workshop series. This game is a 3rd person movement game which utilities collision mechanics and additiona physics to allow the player to push "Jellies" off the map.',
            link: 'https://nmakucsd.github.io/JellyBump/index.html',
            action: 'PLAY',
            active: true,
        },
        {
            number: 4,
            name: 'Tetris (Desktop)',
            role: 'Developer',
            tech: 'HTML, CSS, JavaScript',
            image: '/images/Tetris.png',
            date: 'January 2020',
            dateShort: '1/2020',
            description: 'Tetris is one of my favorite strategy games. I decided to make this game in vanilla Javascript in order to learn the language.',
            link: 'https://nmakucsd.github.io/Tetris/',
            action: 'PLAY',
            active: true,
        },
        {
            number: 5,
            name: 'Rock Paper Scissors Lizard Spock',
            role: 'Developer',
            tech: 'HTML, CSS, JavaScript',
            image: '/images/RPSLS.png',
            date: 'November 2019',
            dateShort: '11/2019',
            description: 'Rock Paper Scissors Lizard Spock is an enhancement of the classic game "Rock Paper Scissors" and was popularized by the American Sitcom "The Big Bang Theory". This simple game was made as an introduction to JavaScript\'s state mechanic. The player plays against a computer which randomly selects a play. The scoreboard reflects the wins and loses between the player and the computer.',
            link: 'https://nmakucsd.github.io/RockPaperScissorsLizardSpock/',
            action: 'PLAY',
            active: true,
        },
        {
            number: 6,
            name: 'SOTA Cyberdragons Robotics Team',
            role: 'Founder, Programmer, Mechanical Engineer',
            tech: 'Java, Python, OpenCV',
            image: '/images/SOTACyberdragons.png',
            date: 'August 2014 - December 2017',
            dateShort: '8/2014 - 12/2017',
            description: 'The SOTA Cyberdragons is a robotics team based in San Francisco, California. We participate in FIRST (For Inspiration and Recognition of Science and Technology), which is an international robotics organizations that includes thousands of teams and hundreds of thousands of students. Our robotics program fosters ingenuity and champions the growth of well-rounded life skills such as communication, proactivity, and leadership. We are a nonprofit organization that runs a high-budget, and rely on sponsor donations, both in-kind and cash, to support the work we do. Started in 2014, SOTA Cyberdragons has been encouraging STEM (Science, Technology, Engineering, and Mathematics) through challenges tackled with modern technology. Throughout the years incoming members will develop a myriad of skills involving, cooperation and coordination. SOTA Cyberdragons is a team of artists from many backgrounds, banded together in order to form a unique innovation.',
            link: 'http://www.team5700.org/',
            action: 'VISIT SITE',
            active: true,
        },
    ],
    experiences: [
        {
            number: 0,
            name: 'Microsoft',
            role: 'Software Engineer',
            tech: 'XPay',
            image: '/images/Microsoft.png',
            date: 'May 2022 - Present',
            dateShort: '5/2022 - Present',
            description: "I am working at Microsoft's E&D Department this summer, working for XPay.",
            link: '',
            action: 'NDA',
            active: true,
        },
        {
            number: 1,
            name: 'ft',
            role: 'Software Engineer Intern',
            tech: 'Bing Ads',
            image: '/images/Microsoft.png',
            date: 'June 2021 - September 2021',
            dateShort: '6/2021 - 9/2021',
            description: "I interned at Microsoft's E&D Department summer 2021, working for Bing Ads.",
            link: '',
            action: 'Not Available',
            active: false,
        },
        {
            number: 2,
            name: 'Toasty',
            role: 'Software Engineering Intern',
            tech: 'Flutter, Ruby on Rails',
            image: '/images/Toasty.png',
            date: 'January 2020 - April 2020',
            dateShort: '1/2020 - 4/2020',
            description: 'Toasty was a startup to make an mobile app driven to make building new social relationships easier. The focus of this technology was to remove initial biases individuals would have before going to events in order to enhance the amount of interactions individuals would actually participate. The app would schedule reservations and match multiple individuals based on interests and involvement. This technology was built with Flutter and Ruby on Rails.',
            link: '',
            action: 'This Project is Under NDA',
            active: false,
        },
        {
            number: 3,
            name: 'Triton XR',
            role: 'Main Software Developer',
            tech: 'HTML, CSS, React, Javascript',
            image: '/images/TritonXR.png',
            date: 'November 2019 - February 2021',
            dateShort: '1/2020 - 2/2021',
            description: 'Triton XR (formerly the "Virtual Reality Club at UCSD") is a student organization at UC San Diego that connects members with the XR industry through workshops, projects, and networking. Our mission is to foster a multidisciplinary community dedicated to exploring and creating Extended Reality (Virtual, Augmented, and Mixed Reality) experiences. I initially joined the officers in order to motivate myself to learn more about 3D technology. I started as an assistant Project Manager and worked my way up to a Project Manager. While the role was motivating, I eventually decided to switch to be a Web Developer, for I felt it could help me get more experience with Sotware Engineering. Currently I am responsible for maintaining the Triton XR website and any upgrades I may have planned in the future.',
            link: 'https://tritonxr.ucsd.edu/',
            action: 'VISIT SITE',
            active: true,
        },
        {
            number: 4,
            name: 'BulkUP E-commerce Web App',
            role: 'Developer and Designer',
            tech: 'MongoDB, Express, React, Node.js',
            image: '/images/BulkUP.png',
            date: 'December 2020 - April 2021',
            dateShort: '12/2020 - 4/2021',
            description: 'This is an E-commerce Web App built to connect produce sellers with restaurant and business owners in order to remove the middleman and allow both sides to have better business and pricing. Sellers are able to view and connect with restaurants nearby while buyers are able to easily see the selection of farmers and wholesale sellers nearby as well. This app is built with MongoDB, Express, React, and NodeJS.',
            link: 'https://my-bulkup-app.herokuapp.com/',
            action: 'VISIT SITE',
            active: true,
        },
        {
            number: 5,
            name: 'Robolink',
            role: 'Robotics Instructor',
            tech: 'Python, RobotC, Vex Robotics',
            image: '/images/Robolink.png',
            date: 'November 2019 - May 2020',
            dateShort: '11/2019 - 5/2020',
            description: 'With my prior experience in robotics competitions and robotics programming completed as I enrolled in UCSD, I decided I wanted to get back into the robotics competition field. Robolink offered a position as a robotics instructor to teach kids not only the basics of programming through robots, but also the many experiences and joys it offers from simplying seeing something move to the excitement of competitions. Robolink provides an opportunity for its students to participate in VEX IQ, an international robotics competition for kids in elementary and middle school. As a coach/instructor, I have to teach my students how to build a proper robot with common robotics concepts, how to program it in RobotC, and help them practice playing the game. I also teach other kids not in the VEX IQ program how to program Arduino based robots.',
            link: 'https://shop.robolink.com/',
            action: 'VISIT SITE',
            active: true,
        },
        {
            number: 6,
            name: 'IEEE',
            role: 'Project Lead',
            tech: 'Onshape, C++, grSim, SLL-Vision',
            image: '/images/IEEE.png',
            date: 'October 2019 - February 2020',
            dateShort: '10/2019 - 2/2020',
            description: 'The RoboCup Soccer annual project at IEEE@UCSD, developed by the RoboCup Federation, is a project about building a group of autonomous soccer robots and developing AI algorithms for them to perform various tactics on the soccer field.',
            link: '',
            action: 'IEEE Robocup 2020 is no longer active',
            active: false,
        },
        {
            number: 7,
            name: 'The Taylor Collaboration',
            role: 'Engineering Intern',
            tech: 'G Code',
            image: '/images/TC.png',
            date: 'May 2017 - July 2017',
            dateShort: '5/2017 - 7/2017',
            description: 'The Taylor Collaboration is a R&D lab for orthopaedic research',
            link: 'https://thetaylorcollaboration.jimdofree.com/',
            action: 'Visit Site',
            active: true,
        },
    ],
};
export default data;