const data = {
    projects:[
        {
            _id: 'BulkUP',
            name: 'BulkUP E-commerce Web App',
            role: 'Developer and Designer',
            tech: 'MongoDB, Express, React, Node.js',
            image: '/images/BulkUP.png',
            date: 'December 2020',
            description: 'This is an E-commerce Web App built to connect produce sellers with restaurant and business owners in order to remove the middleman and allow both sides to have better business and pricing. Sellers are able to view and connect with restaurants nearby while buyers are able to easily see the selection of farmers and wholesale sellers nearby as well. This app is built with MongoDB, Express, React, and NodeJS.',
            link: 'https://my-bulkup-app.herokuapp.com/',
            action: 'VISIT SITE',
        },
        {
            _id: 'Wear-A-Mask',
            name: 'Wear a Mask!',
            role: 'Main Developer',
            tech: 'Unity3D, C#',
            image: '/images/WearAMask.png',
            date: 'January 2021',
            description: 'This Unity game was built by me to start TritonXR\'s, a VR/AR organization in my university, Unity workshop series. This game is a 3rd person movement game which utilities collision mechanics and additiona physics to allow the player to push "Jellies" off the map.',
            link: 'https://nmakucsd.github.io/JellyBump/index.html',
            action: 'PLAY',
        },
        {
            _id: 'Jelly-Bumper',
            name: 'Jelly Bumper',
            role: 'Main Developer',
            tech: 'Unity3D, C#',
            image: '/images/JellyBumpers.png',
            date: 'November 2020',
            description: 'This Unity game was built by me to start TritonXR\'s, a VR/AR organization in my university, Unity workshop series. This game is a 3rd person movement game which utilities collision mechanics and additiona physics to allow the player to push "Jellies" off the map.',
            link: 'https://nmakucsd.github.io/JellyBump/index.html',
            action: 'PLAY',
        },
        {
            _id: 'Tetris',
            name: 'Tetris (Desktop)',
            role: 'Developer',
            tech: 'HTML, CSS, JavaScript',
            image: '/images/Tetris.png',
            date: 'January 2020',
            description: 'Tetris is one of my favorite strategy games. I decided to make this game in vanilla Javascript in order to learn the language.',
            link: 'https://nmakucsd.github.io/Tetris/',
            action: 'PLAY',
        },
        {
            _id: 'RPSLS',
            name: 'Rock Paper Scissors Lizard Spock',
            role: 'Developer',
            tech: 'HTML, CSS, JavaScript',
            image: '/images/RPSLS.png',
            date: 'November 2019',
            description: 'Rock Paper Scissors Lizard Spock is an enhancement of the classic game "Rock Paper Scissors" and was popularized by the American Sitcom "The Big Bang Theory". This simple game was made as an introduction to JavaScript\'s state mechanic. The player plays against a computer which randomly selects a play. The scoreboard reflects the wins and loses between the player and the computer.',
            link: 'https://nmakucsd.github.io/RockPaperScissorsLizardSpock/',
            action: 'PLAY',
        },
        {
            _id: 'SOTACyberdragons',
            name: 'SOTA Cyberdragons',
            role: 'Founder, Programmer, Mechanical Engineer',
            tech: 'Java',
            image: '/images/SOTACyberdragons.png',
            date: 'August 2014 - December 2017',
            description: 'The SOTA Cyberdragons is a robotics team based in San Francisco, California. We participate in FIRST (For Inspiration and Recognition of Science and Technology), which is an international robotics organizations that includes thousands of teams and hundreds of thousands of students. Our robotics program fosters ingenuity and champions the growth of well-rounded life skills such as communication, proactivity, and leadership. We are a nonprofit organization that runs a high-budget, and rely on sponsor donations, both in-kind and cash, to support the work we do. Started in 2014, SOTA Cyberdragons has been encouraging STEM (Science, Technology, Engineering, and Mathematics) through challenges tackled with modern technology. Throughout the years incoming members will develop a myriad of skills involving, cooperation and coordination. SOTA Cyberdragons is a team of artists from many backgrounds, banded together in order to form a unique innovation.',
            link: 'http://www.team5700.org/',
            action: 'VISIT SITE',
        },
    ],
    experiences:[
        {
            _id: 'Toasty',
            name: 'Toasty',
            role: 'Software Engineering Intern',
            tech: 'Flutter, Ruby on Rails',
            image: '/images/Toasty.png',
            date: 'January 2020 - April 2020',
            description: 'Toasty was a startup to make an mobile app driven to make building new social relationships easier. The focus of this technology was to remove initial biases individuals would have before going to events in order to enhance the amount of interactions individuals would actually participate. The app would schedule reservations and match multiple individuals based on interests and involvement. This technology was built with Flutter and Ruby on Rails.',
            link: 'http://www.team5700.org/',
            action: 'NA',
        },
        {
            _id: 'BulkUP',
            name: 'BulkUP E-commerce Web App',
            role: 'Developer and Designer',
            tech: 'MongoDB, Express, React, Node.js',
            image: '/images/BulkUP.png',
            date: 'December 2020',
            description: 'This is an E-commerce Web App built to connect produce sellers with restaurant and business owners in order to remove the middleman and allow both sides to have better business and pricing. Sellers are able to view and connect with restaurants nearby while buyers are able to easily see the selection of farmers and wholesale sellers nearby as well. This app is built with MongoDB, Express, React, and NodeJS.',
            link: 'https://bulkup-app.herokuapp.com/landing',
            action: 'VISIT SITE',
        },
    ],
};
export default data;